### ISSUE TITLE
Upstream Stitch Walkthrough

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/api-quickstart#3]
Allow anyone to try out the Stitch POC environment completely upstream.

- Start from a basis of the MGC setup scripts, which install & setup kind clusters, Kuadrant, istio, metalLB, cert-manager etc.
- Layer in Petstore/API setup scripts:
  - [x] #6  (basically: copy https://github.com/Kuadrant/multicluster-gateway-controller/pull/760)
  - [x] #5
  - [x] #7 (similar to https://github.com/Kuadrant/multicluster-gateway-controller/pull/756)
  - [x] #8 (similar to https://github.com/Kuadrant/multicluster-gateway-controller/pull/756)

More info in internal doc https://docs.google.com/document/d/1qUS4Y7lcIkvggs-tA5cGyx0rUQo1J0oNEIZ-ktHghZI/edit#heading=h.psbl479r39x6

### Walkthrough Doc

Copy and adapt the existing [MGC multi cluster walkthrough](https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/) to:

* [x] #4
* [x] #9
* [x] #10
* [x] #11
* [x] #12
* [x] #29 
* [x] #36

Add these docs to the README.md
